name: SIMANIS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "mysql://root@localhost:3306/simanis"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Prisma Generate
        run: bun x prisma generate
        env:
          PRISMA_CLIENT_ENGINE_TYPE: library

      - name: Run Lint
        run: bun run lint

      - name: Install Playwright Browsers
        run: bun x playwright install --with-deps chromium

      - name: Run Tests
        run: bun x vitest run

      - name: Build
        run: bun run build
